modLoader="groovyfml"
loaderVersion="[5,)"
issueTrackerURL="https://github.com/TheSledgeHammer/GroovyModels/issues"
[[mods]]
    modId="groovymodels"
    version="${version}"
    displayName="GroovyModels"
    #updateJSONURL="http://myurl.me/" #optional
    displayURL="https://github.com/TheSledgeHammer/GroovyModels"
    #logoFile="groovymclogo.png"
    credits="Apache Groovy"
    authors="TheSledgeHammer"
    description='''
    An Apache Groovy Model API for Minecraft
    '''
