modLoader="groovyfml"
loaderVersion="[3,)"
issueTrackerURL="https://github.com/TheSledgeHammer/GroovyMC/issues"
[[mods]]
    modId="groovymc"
    version="${version}"
    displayName="GroovyMC"
    #updateJSONURL="http://myurl.me/" #optional
    displayURL="https://github.com/TheSledgeHammer/GroovyMC"
    #logoFile="groovymclogo.png"
    credits="Apache Groovy"
    authors="TheSledgeHammer"
    description='''
    An Apache Groovy Compatibility Library
    '''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.groovymc]]
    modId="groovyforge"
    mandatory=true
    versionRange="[3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.groovymc]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.groovymc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3)"
    ordering="NONE"
    side="BOTH"